spring:
  datasource:
    url: jdbc:mysql://211.188.61.117:3306/bungmakase?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true
    username: bungmakase
    password: bungmakase
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20       # 최대 커넥션 수
      minimum-idle: 5             # 최소 유휴 커넥션 수
      idle-timeout: 30000         # 유휴 커넥션 유지 시간 (밀리초)
      max-lifetime: 1800000       # 커넥션의 최대 생존 시간 (밀리초)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false           # Hibernate SQL 로그 비활성화
        format_sql: false         # Hibernate SQL 포맷 비활성화
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: 211.188.61.117      # Redis 호스트
      port: 6379                 # Redis 포트

  task:
    execution:
      pool:
        core-size: 10            # 기본적으로 유지되는 스레드 수
        max-size: 50             # 최대 스레드 수
        queue-capacity: 100      # 작업 대기열 크기
      thread-name-prefix: "AsyncExecutor-" # 스레드 이름 접두사

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=300s

logging:
  level:
    org.hibernate.SQL: debug    # Hibernate SQL 디버깅


kakao:
  client-id: "0ed5f2288c7f985d06f7ca5610740c23"
  redirect-uri: "https://bungmakase.shop/api/auth/kakao/callback"

jwt:
  secret-key: "+M/FwZHNfp1U576hW3XaPByErG3p83NqEXRRhG3EYwXrvkrPxb5TAvjqKZQI/QCbaWrU3gW+b1BaT35zpxyz3Q=="

ncp:
  s3:
    endpoint: "https://kr.object.ncloudstorage.com"  # NCP Object Storage 엔드포인트
    region: kr-standard  # NCP Region
    access-key: "ncp_iam_BPAMKR37jeWJYOAf9FFP"
    secret-key: "ncp_iam_BPKMKRYiwD6tGkpUTI8IYZNEq0V63rq2Ti"
    bucket: bungmakase-bucket



server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: bungmakase
    key-store-type: PKCS12
    enabled: true
  tomcat:
    threads:
      max: 200                  # 최대 스레드 수
      min-spare: 20             # 최소 대기 스레드 수